<Project>
  <PropertyGroup>
    <PowerToysVersion>0.100.0</PowerToysVersion>

    <PowerToysArchitecture
      Condition="'$(PowerToysArchitecture)' == ''">x64</PowerToysArchitecture>

    <PowerToysDepsDir>$(MSBuildThisFileDirectory).deps\powertoys\$(PowerToysVersion)\$(PowerToysArchitecture)</PowerToysDepsDir>
    <PluginVersion>0.1.0</PluginVersion>
  </PropertyGroup>
</Project>